<?php
$form = $this->form;
$form->setAttribute('action', $this->url('email', ['action' => 'create']));
$form->prepare();

echo $this->doctype('HTML5');
?>

<html lang="en">
<head>
    <title>Simple Email Application</title>
</head>
<body>
<div class="container mt-5">
    <div class="row">
        <div class="col-md-6 offset-md-3 d-block-labels">
            <h1 class="text-center mb-4">Simple Email Application</h1>
            <a class="card-link" href="<?php echo $this->url('email', ['action' => 'list']) ?>">Sent mails</a>
            <hr>

            <?php foreach (['error', 'success'] as $messageType) : ?>
                <?php if ($message = $this->flashMessenger()->getCurrentMessages($messageType)) : ?>
                    <div class="alert alert-<?php echo $messageType == 'error' ? 'danger' : $messageType; ?>">
                        <?php echo implode('<br>', $message); ?>
                    </div>
                <?php endif; ?>
            <?php endforeach; ?>

            <?php
                echo $this->form()->openTag($form);
                echo $this->formHidden($form->get('csrf'));
                echo $this->formRow($form->get('name'));
                echo $this->formRow($form->get('email'));
                echo $this->formRow($form->get('phone'));
                echo $this->formRow($form->get('content'));
                echo $this->formSubmit($form->get('submit'));
                echo $this->form()->closeTag();
            ?>
        </div>
    </div>
</div>
</body>
</html>
