version: '3.7'

services:
  app:
    build:
      context: .
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_DATABASE=mydatabase
      - DB_USERNAME=myuser
      - DB_PASSWORD=mypassword
    working_dir: /var/www
    volumes:
      - .:/var/www/
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - defaultnetwork

  db:
    image: mysql:5.7.22
    environment:
      - MYSQL_ROOT_PASSWORD=mypassword
      - MYSQL_DATABASE=mydatabase
      - MYSQL_USER=myuser
      - MYSQL_PASSWORD=mypassword
    ports:
      - "3306:3306"
    expose:
      - '3306'
    networks:
      - defaultnetwork

  server:
    image: nginx:stable-alpine
    volumes:
      - .:/var/www/
      - ./config/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - app
    networks:
      - defaultnetwork

networks:
  defaultnetwork:
    driver: bridge