<?php
/**
 * @var Laminas\View\Renderer\PhpRenderer $this
 */
?>
<?php echo $this->doctype() ?>
<html lang="en">
<head>
    <title>Simple Email Application</title>
    <meta charset="utf-8">
    <?php echo $this->headTitle('Laminas MVC Skeleton')->setSeparator(' - ')->setAutoEscape(false) ?>

    <?php echo $this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1.0')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
    ?>

    <!-- Le styles -->
    <?php echo $this->headLink([
        'rel' => 'shortcut icon',
        'type' => 'image/vnd.microsoft.icon',
        'href' => $this->basePath() . '/img/favicon.ico'
    ])
        ->prependStylesheet($this->basePath('css/style.css'))
        ->prependStylesheet($this->basePath('css/bootstrap.min.css'))
    ?>

    <!-- Scripts -->
    <?php echo $this->headScript() ?>
</head>
<body>
<div class="container">
    <?php echo $this->content ?>
</div>
<?php echo $this->inlineScript()
    ->prependFile($this->basePath('js/bootstrap.min.js'))
    ->prependFile($this->basePath('js/jquery-3.5.1.min.js')) ?>
</body>
</html>
