<?php echo $this->doctype('HTML5') ?>

<html lang="en">
<head>
    <title>Simple Email Application</title>
</head>
<body>
<div class="container mt-4">
    <h1 class="text-center mb-4">List of Sent Emails</h1>
    <a class="card-link" href="<?php echo $this->url('email', ['action' => 'index']) ?>">New</a>
    <hr>
    <?php if (!empty($profiles)): ?>
        <div class="list-group text-truncate">
            <?php foreach ($profiles as $profile): ?>
                <div class="card">
                    <div class="card-body">
                        <h5 class="card-title"><?php echo $profile->getName() ?></h5>
                        <h6 class="card-subtitle mb-2 text-muted"><?php echo $profile->getEmail() ?></h6>
                        <p class="card-text mb-2"><?php echo $profile->getPhone() ?></p>
                        <p class="card-text text-truncate"><?php echo $profile->getContent() ?></p>
                    </div>
                </div>
            <?php endforeach; ?>
        </div>
    <?php else: ?>
        <p>No emails found</p>
    <?php endif; ?>
</div>
</body>
</html>
